image:https://travis-ci.org/superseacat/bootreact.svg?branch=master["Build Status", link="https://travis-ci.org/superseacat/bootreact"]

image:https://snyk.io//test/github/superseacat/bootreact/badge.svg?targetFile=package.json["Known Vulnerabilities", link="https://snyk.io//test/github/superseacat/bootreact?targetFile=package.json"]

image:https://snyk.io//test/github/superseacat/bootreact/badge.svg?targetFile=pom.xml["Known Vulnerabilities", link="https://snyk.io//test/github/superseacat/bootreact?targetFile=pom.xml"]

== Build

to run locally (JDK 8+ & Apache Maven required). add DB password to `spring.datasource.password=` (or further change the DB settings) at: link:/src/main/resources/application.properties[application.properties], then

....
mvn clean install
java -jar target/react-and-spring-data-rest-events-0.0.1-SNAPSHOT.jar
....

and go to http://localhost:8080[localhost:8080]

to check the application online, visit AWS: http://analysis-app.eu-north-1.elasticbeanstalk.com/[http://analysis-app.aws.com]

== ToDos

* [x] add app skeleton
* [x] update back-end data model to `DataSet`
* [x] simplify data model with lombok
* [x] simplify project back-end structure
* [x] rename REST endpoints everywhere
* [x] add sample (failing) integration test
* [x] configure app to work with Postgre (AWS RDS)
* [x] configure the JSONB Postgre feature
* [x] add bootstrap
* [x] configure deployment to AWS BeansTalk with Travis
* [x] plugin dependencies security analysis tool (Snyk)
* [x] add test for the used REST endpoints
* [x] incorporate IT testing into deployment pipeline
* [x] add input validation on back-end side
* [ ] add input validation on endpoint side
* [ ] add proper endpoint error handling
* [ ] improve react app structure (cut at least into modules)
* [ ] draw tests for react components
* [ ] incorporate UI testing into deployment pipeline
* [ ] improve front-end functionality
* [ ] add JPA tests
* [ ] add Spring REST Docs to the project
* [ ] add coverage exposure tool
* [ ] check the licenses compatibility
* [ ] adventure (custom fields to the `DataSet`
* [ ] cloudformate deployment